# -*- coding: utf-8 -*-
"""Generator — 从字段定义产出三份产物。

1. 任务配置片段（并入 pipeline.yaml / plugins.yaml 的实例条目）
2. JSON Schema（进受控 schema 注册表命名空间）
3. FormSpec（供 W7 task-config.html 渲染表单）
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from schema_editor.editor import BUILTIN_PROFILES


# ── 1. 任务配置片段 ──

def generate_task_config(definition: dict[str, Any]) -> dict[str, Any]:
    """从字段定义产出 TaskConfigDTO 兼容的任务配置片段。

    返回值可并入 pipeline.yaml / plugins.yaml。
    """
    task_id = uuid4().hex
    dataset = definition.get("dataset", "unnamed")
    source_id = definition.get("source_id", "source_a")
    profile_id = definition.get("profile_id", "custom")
    target_url = definition.get("target_url", "")
    fields = definition.get("fields", [])
    plugins = definition.get("plugins", {})

    # 构建 config_snapshot
    config_snapshot: dict[str, Any] = {
        "fields": fields,
        "selectors": definition.get("selectors", {}),
        "max_pages": definition.get("max_pages", 10),
    }
    if target_url:
        config_snapshot["list_url"] = target_url

    return {
        "task_id": task_id,
        "dataset": dataset,
        "source_id": source_id,
        "profile_id": profile_id,
        "target_url": target_url,
        "config_revision": 1,
        "config_snapshot": config_snapshot,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "plugins": plugins,
    }


# ── 2. JSON Schema ──

def generate_json_schema(definition: dict[str, Any]) -> dict[str, Any]:
    """从字段定义产出 JSON Schema（draft-07 兼容）。

    schema_id 格式: {dataset}.v1
    """
    dataset = definition.get("dataset", "unnamed")
    fields = definition.get("fields", [])
    profile_id = definition.get("profile_id", "custom")

    properties: dict[str, Any] = {}
    required: list[str] = []

    for field in fields:
        name = field["name"]
        ftype = field.get("type", "string")

        prop: dict[str, Any] = {"type": ftype}
        if field.get("description"):
            prop["description"] = field["description"]
        if "enum" in field:
            prop["enum"] = field["enum"]
        if ftype in ("integer", "number"):
            if "minimum" in field:
                prop["minimum"] = field["minimum"]
            if "maximum" in field:
                prop["maximum"] = field["maximum"]

        properties[name] = prop
        if field.get("required"):
            required.append(name)

    # 追加 profile 扩展 schema 引用
    profile = BUILTIN_PROFILES.get(profile_id, {})
    schema_ids = profile.get("schema_ids", [])

    schema: dict[str, Any] = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": f"{dataset}.v1",
        "title": f"{dataset} record schema",
        "description": f"Auto-generated by schema_editor for dataset '{dataset}'",
        "type": "object",
        "properties": properties,
        "additionalProperties": False,
    }
    if required:
        schema["required"] = required
    if schema_ids:
        schema["$comment"] = f"Profile '{profile_id}' extends: {', '.join(schema_ids)}"

    return schema


# ── 3. FormSpec ──

def generate_form_spec(definition: dict[str, Any]) -> dict[str, Any]:
    """从字段定义产出 FormSpec（供 W7 task-config.html 渲染表单）。

    FormSpec 是 UI 友好的字段描述，包含 widget hints。
    """
    dataset = definition.get("dataset", "unnamed")
    fields = definition.get("fields", [])

    widgets: list[dict[str, Any]] = []

    for field in fields:
        name = field["name"]
        ftype = field.get("type", "string")

        widget: dict[str, Any] = {
            "name": name,
            "label": field.get("description", name),
            "type": _type_to_widget(ftype, field),
            "required": field.get("required", False),
        }

        if "enum" in field:
            widget["type"] = "select"
            widget["options"] = field["enum"]
        if ftype in ("integer", "number"):
            if "minimum" in field:
                widget["min"] = field["minimum"]
            if "maximum" in field:
                widget["max"] = field["maximum"]

        widgets.append(widget)

    return {
        "dataset": dataset,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "widgets": widgets,
    }


def _type_to_widget(ftype: str, field: dict) -> str:
    """映射 JSON Schema type → FormSpec widget type。"""
    mapping = {
        "string": "text",
        "integer": "number",
        "number": "number",
        "boolean": "checkbox",
        "array": "tag-input",
        "object": "json-editor",
    }
    return mapping.get(ftype, "text")


# ── 4. 校验入口 ──

def validate_generated_config(task_config: dict[str, Any]) -> dict[str, Any]:
    """调用 config.validator 校验生成的任务配置。

    返回 {"errors": [...], "warnings": [...], "valid": bool}
    """
    errors: list[str] = []
    warnings: list[str] = []

    # 基本字段校验
    required_keys = ("task_id", "dataset", "source_id", "profile_id", "target_url", "config_snapshot")
    for key in required_keys:
        if key not in task_config:
            errors.append(f"缺少必填字段: {key}")

    # config_snapshot 内 fields 校验
    snapshot = task_config.get("config_snapshot", {})
    fields = snapshot.get("fields", [])
    if not fields:
        warnings.append("config_snapshot.fields 为空")

    seen_names: set[str] = set()
    for field in fields:
        if "name" not in field:
            errors.append(f"字段缺少 name: {field}")
            continue
        if field["name"] in seen_names:
            errors.append(f"重复字段名: {field['name']}")
        seen_names.add(field["name"])
        if "type" not in field:
            errors.append(f"字段 '{field['name']}' 缺少 type")

    # 试跑 config.validator（如可用）
    try:
        from config.validator import validate_school_config
        # 构造 validator 兼容的输入格式
        school_config = _task_config_to_school_config(task_config)
        validator_errors = validate_school_config(school_config)
        for err in validator_errors:
            if err.level == "error":
                errors.append(str(err))
            else:
                warnings.append(str(err))
    except (ImportError, Exception):
        warnings.append("config.validator 不可用，跳过完整校验")

    return {
        "errors": errors,
        "warnings": warnings,
        "valid": len(errors) == 0,
    }


def _task_config_to_school_config(task_config: dict[str, Any]) -> dict[str, Any]:
    """将 TaskConfigDTO 格式转换为 config.validator 兼容的学校配置格式。"""
    snapshot = task_config.get("config_snapshot", {})
    fields = snapshot.get("fields", [])

    return {
        "university": task_config.get("dataset", "unknown"),
        "categories": [{
            "college": task_config.get("source_id", "default"),
            "category": "mechanical",
            "faculty": {
                "list_url": task_config.get("target_url", ""),
                "list_type": task_config.get("plugins", {}).get("acquire", "static_html"),
                "enabled": True,
            },
            "notice": {"enabled": False},
        }],
        "fields": fields,
    }


# ── 5. 组合入口 ──

def generate_all(definition: dict[str, Any]) -> dict[str, Any]:
    """一次性产出三份产物 + 校验结果。"""
    task_config = generate_task_config(definition)
    json_schema = generate_json_schema(definition)
    form_spec = generate_form_spec(definition)
    validation = validate_generated_config(task_config)

    return {
        "task_config": task_config,
        "json_schema": json_schema,
        "form_spec": form_spec,
        "validation": validation,
    }
